// @ts-check
const { test, expect } = require('@playwright/test');
const path = require('path');

test.describe('tutorial inline Markdown rendering', () => {
  test('renders code spans in step titles and details summaries without exposing raw backticks', async ({ page }) => {
    await page.setContent(`
      <!doctype html>
      <html>
        <body>
          <h2 id="title"></h2>
          <details>
            <summary>\u{1F4D6} What about \`monkeypatch\`?</summary>
            <p>Body</p>
          </details>
        </body>
      </html>
    `);
    await page.addScriptTag({
      path: path.resolve(__dirname, '..', 'js', 'tutorial-inline-markdown.js'),
    });

    await page.evaluate(() => {
      document.getElementById('title').innerHTML =
        window.SebookInlineMarkdown.render('Library Doubles with `unittest.mock`: Same Roles, Less Typing');
      window.SebookInlineMarkdown.renderSummaries(document);
    });

    const title = page.locator('#title');
    await expect(title).toContainText('Library Doubles with unittest.mock: Same Roles, Less Typing');
    await expect(title).not.toContainText('`');
    await expect(title.locator('code')).toHaveText('unittest.mock');

    const summary = page.locator('summary');
    await expect(summary).toContainText('What about monkeypatch?');
    await expect(summary).not.toContainText('`');
    await expect(summary.locator('code')).toHaveText('monkeypatch');
  });

  test('strips unsafe inline HTML generated by marked-compatible input', async ({ page }) => {
    await page.setContent('<!doctype html><html><body></body></html>');
    await page.addScriptTag({
      path: path.resolve(__dirname, '..', 'js', 'tutorial-inline-markdown.js'),
    });

    const html = await page.evaluate(() => {
      window.marked = {
        parseInline: () => 'Safe <code>code</code> <img src=x onerror=alert(1)> <script>alert(1)</script>',
      };
      return window.SebookInlineMarkdown.render('ignored');
    });

    expect(html).toContain('<code>code</code>');
    expect(html).not.toContain('<img');
    expect(html).not.toContain('<script');
    expect(html).not.toContain('onerror');
  });

  test('print tutorial renders inline Markdown in real step heading surfaces', async ({ page }) => {
    await page.goto('/SEBook/tools/test-doubles-tutorial/print.html');

    const title = page.locator('.step-title').filter({
      hasText: 'Library Doubles with unittest.mock: Same Roles, Less Typing',
    });
    await expect(title).toHaveCount(1);
    await expect(title.locator('code')).toHaveText('unittest.mock');
    await expect(title).not.toContainText('`');

    const summary = page.locator('summary').filter({ hasText: 'What about monkeypatch?' });
    await expect(summary).toHaveCount(1);
    await expect(summary.locator('code')).toHaveText('monkeypatch');
    await expect(summary).not.toContainText('`');
  });
});
