$(function(){
  $("#functionality").load("functionality.html"); 
});
$(function(){
  $("#parameters").load("parameters.html"); 
});
$(function(){
  $("#presets").load("presets.html"); 
});
$(function(){
  $("#demo").load("demo.html"); 
});
$(function(){
  $("#about").load("about.html"); 
});
$(function(){
  $("#footer").load("footer.html"); 
});
$(function(){
  $("#walkthrough").load("walkthrough.html"); 
});
$(function(){
  $("#examples").load("examples.html"); 
});
$(function(){
  $("#painting").load("parameter_painting.html"); 
});
$(function(){
  $("#features").load("features.html"); 
});
