/**
 * WebVTT captions for both cuts of the SE Book teaser, built from the
 * storyboard so captions, transcript, and video share one script:
 *
 *   - instrumental cut: each scene's `sound` line, shown until the next
 *     scene that has one (WCAG 1.2.2 — the only audio is music);
 *   - audio-described cut: the same music lines plus every narration line,
 *     timed to when the narrator actually speaks it.
 */
'use strict';

function timestamp(seconds) {
  const totalMs = Math.round(seconds * 1000);
  const ms = String(totalMs % 1000).padStart(3, '0');
  const s = String(Math.floor(totalMs / 1000) % 60).padStart(2, '0');
  const m = String(Math.floor(totalMs / 60000)).padStart(2, '0');
  return `00:${m}:${s}.${ms}`;
}

function toVtt(cues, note) {
  const blocks = cues
    .slice()
    .sort((a, b) => a.start - b.start)
    .map((cue, index) => `${index + 1}\n${timestamp(cue.start)} --> ${timestamp(cue.end)}\n${cue.text}`);
  return `WEBVTT\n\nNOTE\n${note}\n\n${blocks.join('\n\n')}\n`;
}

/** Music captions: one cue per `sound` line, lasting until the next one. */
function soundCues(storyboard) {
  const scored = storyboard.scenes.filter((scene) => scene.sound);
  return scored.map((scene, index) => ({
    start: scene.start,
    end: index + 1 < scored.length ? scored[index + 1].start : storyboard.duration,
    text: scene.sound,
  }));
}

const GENERATED_NOTE = 'Generated by scripts/sebook-teaser/render.js from _data/sebook_teaser.yml; edit that file, not this one.';

function instrumentalCaptions(storyboard) {
  return toVtt(soundCues(storyboard), `${GENERATED_NOTE}\nThe teaser's only audio is instrumental music.`);
}

/**
 * `lines` are the timed narration lines returned by renderNarration(). Each
 * caption lingers a little after the voice stops, but never past the next line.
 */
function describedCaptions(storyboard, lines) {
  const narration = lines.map((line, index) => ({
    start: line.start,
    end: Math.min(line.end + 0.4, index + 1 < lines.length ? lines[index + 1].start : storyboard.duration),
    text: line.text,
  }));
  return toVtt([...soundCues(storyboard), ...narration], `${GENERATED_NOTE}\nNarration describes the on-screen text over the music.`);
}

module.exports = { describedCaptions, instrumentalCaptions };
